### ISSUE TITLE
Change to output layers size?

### ISSUE THREAD

**Issue by mixmixmix** [ctorney/uavTracker#44]
The [final layers of yolo](https://github.com/ctorney/aerial_wildlife_detection/blob/182bcf25b0a62642c22f4173be0406f32bb8ab7b/ai/models/tensorflow/functional/_yolo_3/model.py#L165), such as (large):
```
yolo_82a = _conv_block(yolo_82_pre_layer, [{'filter':  3*out_size, 'kernel': 1, 'stride': 1, 'bnorm': False, 'leaky': False,'train': headtrainable, 'layer_idx': 1081}], skip=False, train=trainable)
```
are getting reshaped in the last stage with your function
```
def reshape_last_layer(out_size):
    def func(x):
        # reshape last 2 dimensions 
        in_b      = tf.shape(x)[0]
        in_h      = tf.shape(x)[1]
        in_w      = tf.shape(x)[2]

        final_l = tf.reshape(x, [in_b, in_h, in_w, 3, out_size])
        return final_l
    return Lambda(func)
```
I think, previously this layer would be downsampled during reshaping

https://github.com/ctorney/uavTracker/blob/610f55aa063c074e8188d0ef02991d1c6ef66009/models/yolo_models.py#L411

Could you explain if it is indeed a change or am I misunderstanding how reshaping works there?

**Comment by ctorney** [comment]
the reshaping should work in the same way as before but instead of specifying the image size as parameters it takes it from the shape of the tensor at the end - you could get the width and height from the image but then you'd need a separate function for the large/medium/small grids (or pass in a divisor).

There is another change though - this version splits off the class labels and the objectness and bounding box predictions. This is so you can transfer learn on a new set of classes but keep what's been learned previously about objects and boxes.

**Comment by mixmixmix** [comment]
I have moved the reshaping to the get_layer functions as it was previously there and in deepBeastlinker we were had "reshape" as last layer:
https://github.com/ctorney/uavTracker/blob/4a01fab73c404dffd66afc8e7d8269d3edc12f0a/models/yolo_models.py#L207-L210

and converting output part was adjusted to return the same outputs as before.

https://github.com/ctorney/uavTracker/blob/4a01fab73c404dffd66afc8e7d8269d3edc12f0a/models/yolo_models.py#L223-L260
